version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./Files/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    volumes:
      - ./Files/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ContraseñaSecreta123
    depends_on:
      - prometheus
    ports:
      - '3000:3000'

volumes:
  grafana-data: