{
 "title": "Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(container) (nginx_up{namespace=\"dllacsa\",service=\"nginx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico de conexiones activas (Num)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "nginx_connections_active{service=\"nginx\", namespace=\"dllacsa\" }",
     "legendFormat": "{{namespace}} : {{job}}"
    }
   ]
  },
  {
   "title": "Histórico de conexiones procesadas (Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "irate(nginx_connections_handled{service=\"nginx\", namespace=\"dllacsa\" }[5m])",
     "legendFormat": "{{namespace}} : {{job}}"
    }
   ]
  },
  {
   "title": "Last scrape",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{namespace=\"dllacsa\", service=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico de peticiones HTTP totales (Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{service=\"nginx\",namespace=\"dllacsa\"}[5m])",
     "legendFormat": "{{namespace}} : {{job}}"
    }
   ]
  },
  {
   "title": "Porcentaje de uso de CPU actual (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^.*\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico del uso de CPU del container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^.*\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*\"}) * 100",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*\"})",
     "legendFormat": "Limite cpu"
    }
   ]
  },
  {
   "title": "Histórico del uso de memoria del container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*\"})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\"})",
     "legendFormat": "Limite memoria"
    }
   ]
  }
 ]
}