version: '3.7'
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./Files/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ContraseñaSecreta123
    ports:
      - '3000:3000'

volumes:
  grafana-data: